import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Navbar from "@/components/navbar/Navbar";
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from "sonner";
import LoginModal from "@/components/signin/loginModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><Provider>
      <NextTopLoader color="#E94C88" />
        <Navbar />{children}<Toaster /><LoginModal /></Provider></body>
    </html>
  );
}
